# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-26 20:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pythontest', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokes',
            name='pokes',
            field=models.ManyToManyField(to='pythontest.Users'),
        ),
        migrations.RemoveField(
            model_name='pokes',
            name='pokee',
        ),
        migrations.AddField(
            model_name='pokes',
            name='pokee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pokee', to='pythontest.Users'),
        ),
    ]
