# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-26 20:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pythontest', '0002_auto_20161126_2015'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pokes',
            name='pokes',
        ),
        migrations.AddField(
            model_name='users',
            name='pokes',
            field=models.ManyToManyField(to='pythontest.Pokes'),
        ),
    ]
