# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-28 02:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pythontest', '0003_auto_20161126_2022'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quotes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=21)),
                ('message', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='pokes',
            name='pokee',
        ),
        migrations.RemoveField(
            model_name='pokes',
            name='poker',
        ),
        migrations.RemoveField(
            model_name='users',
            name='pokes',
        ),
        migrations.DeleteModel(
            name='Pokes',
        ),
        migrations.AddField(
            model_name='quotes',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creator', to='pythontest.Users'),
        ),
        migrations.AddField(
            model_name='quotes',
            name='favorite',
            field=models.ManyToManyField(to='pythontest.Users'),
        ),
    ]
