# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-28 02:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pythontest', '0004_auto_20161128_0221'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='birth',
            field=models.DateField(null=True),
        ),
    ]
